{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: rent
    component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app: rent
    component: postgresql
{{- end }}