apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalog
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      {{- if .Values.mongodb.enabled }}
      initContainers:
        - name: load-data
          image: {{ .Values.image }}
          command:
            - yarn
            - load
          env:
            - name: MONGODB_USERNAME
              value: {{ .Values.mongodb.auth.username }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.auth.password }}
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodb.auth.database }}
            - name: MONGODB_HOST
              value: mongodb
      {{- end }}
      containers:
        - name: catalog
          image: {{ .Values.image }}
          env:
            - name: MONGODB_USERNAME
              value: {{ .Values.mongodb.auth.username }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.auth.password }}
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodb.auth.database }}
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /catalog/healthz
              port: 8080
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /catalog/healthz
              port: 8080
