api:
  enabled: true
  image: ""
  replicaCount: 1

worker:
  enabled: true
  image: ""
  replicaCount: 1

kafka:
  enabled: true
  image:
    repository: apache/kafka
    tag: "3.7.0"
  auth:
    enabled: false
  storage:
    size: 1Gi
    storageClass: ""
  service:
    port: 9092

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "16"
  auth:
    postgresPassword: "okteto"
    username: "okteto"
    password: "okteto"
    database: "rentals"
  storage:
    size: 1Gi
    storageClass: ""
  service:
    port: 5432

