
replicaCount: 1
image: ""

# MongoDB Configuration
mongodb:
  enabled: true
  image:
    repository: mongo
    tag: "7"
  auth:
    enabled: true
    username: "okteto"
    password: "okteto"
    database: "okteto"
  storage:
    size: 1Gi
    storageClass: ""
  service:
    port: 27017
